name: build push update base

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: 'your-dockerhub-username' # replace with your Docker Hub username
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }} # Docker Hub token from GitHub secrets
  IMAGE_NAME: 'appbase' # replace with your base Docker image name
  IMAGE_TAG: 'latest' # replace with your Docker image tag

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo to runner
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      
      - name: Build & Publish Docker Image
        run: |
          docker build -f ${GITHUB_WORKSPACE}/Dockerfile -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
